

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    public sealed partial class REF_STATUS : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.REF_STATUS, global::LightSwitchApplication.REF_STATUS.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the REF_STATUS entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public REF_STATUS()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public REF_STATUS(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.REF_STATUS> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.REF_STATUS.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void REF_STATUS_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void REF_STATUS_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public short StatusID
        {
            get
            {
                return global::LightSwitchApplication.REF_STATUS.DetailsClass.GetValue(this, global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties.StatusID);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StatusID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StatusID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StatusID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Name
        {
            get
            {
                return global::LightSwitchApplication.REF_STATUS.DetailsClass.GetValue(this, global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties.Name);
            }
            set
            {
                global::LightSwitchApplication.REF_STATUS.DetailsClass.SetValue(this, global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties.Name, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Description
        {
            get
            {
                return global::LightSwitchApplication.REF_STATUS.DetailsClass.GetValue(this, global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties.Description);
            }
            set
            {
                global::LightSwitchApplication.REF_STATUS.DetailsClass.SetValue(this, global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties.Description, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> CreatedDate
        {
            get
            {
                return global::LightSwitchApplication.REF_STATUS.DetailsClass.GetValue(this, global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties.CreatedDate);
            }
            set
            {
                global::LightSwitchApplication.REF_STATUS.DetailsClass.SetValue(this, global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties.CreatedDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedDate_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string CreatedBy
        {
            get
            {
                return global::LightSwitchApplication.REF_STATUS.DetailsClass.GetValue(this, global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties.CreatedBy);
            }
            set
            {
                global::LightSwitchApplication.REF_STATUS.DetailsClass.SetValue(this, global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties.CreatedBy, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> ModifiedDate
        {
            get
            {
                return global::LightSwitchApplication.REF_STATUS.DetailsClass.GetValue(this, global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties.ModifiedDate);
            }
            set
            {
                global::LightSwitchApplication.REF_STATUS.DetailsClass.SetValue(this, global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties.ModifiedDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedDate_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ModifiedBy
        {
            get
            {
                return global::LightSwitchApplication.REF_STATUS.DetailsClass.GetValue(this, global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties.ModifiedBy);
            }
            set
            {
                global::LightSwitchApplication.REF_STATUS.DetailsClass.SetValue(this, global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties.ModifiedBy, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.RESOURCE> RESOURCEs
        {
            get
            {
                return global::LightSwitchApplication.REF_STATUS.DetailsClass.GetValue(this, global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties.RESOURCEs);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.RESOURCE> RESOURCEsQuery
        {
            get
            {
                return global::LightSwitchApplication.REF_STATUS.DetailsClass.GetQuery(this, global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties.RESOURCEs);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.REF_STATUS,
                global::LightSwitchApplication.REF_STATUS.DetailsClass,
                global::LightSwitchApplication.REF_STATUS.DetailsClass.IImplementation,
                global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.REF_STATUS, global::LightSwitchApplication.REF_STATUS.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.REF_STATUS, global::LightSwitchApplication.REF_STATUS.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties.StatusID;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.REF_STATUS, global::LightSwitchApplication.REF_STATUS.DetailsClass>.Entry
                __REF_STATUSEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.REF_STATUS, global::LightSwitchApplication.REF_STATUS.DetailsClass>.Entry(
                    global::LightSwitchApplication.REF_STATUS.DetailsClass.__REF_STATUS_CreateNew,
                    global::LightSwitchApplication.REF_STATUS.DetailsClass.__REF_STATUS_Created,
                    global::LightSwitchApplication.REF_STATUS.DetailsClass.__REF_STATUS_AllowSaveWithErrors);
            private static global::LightSwitchApplication.REF_STATUS __REF_STATUS_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.REF_STATUS> es)
            {
                return new global::LightSwitchApplication.REF_STATUS(es);
            }
            private static void __REF_STATUS_Created(global::LightSwitchApplication.REF_STATUS e)
            {
                e.REF_STATUS_Created();
            }
            private static bool __REF_STATUS_AllowSaveWithErrors(global::LightSwitchApplication.REF_STATUS e)
            {
                bool result = false;
                e.REF_STATUS_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.REF_STATUS, global::LightSwitchApplication.REF_STATUS.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.REF_STATUS, global::LightSwitchApplication.REF_STATUS.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.REF_STATUS, global::LightSwitchApplication.REF_STATUS.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_STATUS, global::LightSwitchApplication.REF_STATUS.DetailsClass, short> StatusID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties.StatusID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_STATUS, global::LightSwitchApplication.REF_STATUS.DetailsClass, short>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_STATUS, global::LightSwitchApplication.REF_STATUS.DetailsClass, string> Name
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties.Name) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_STATUS, global::LightSwitchApplication.REF_STATUS.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_STATUS, global::LightSwitchApplication.REF_STATUS.DetailsClass, string> Description
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties.Description) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_STATUS, global::LightSwitchApplication.REF_STATUS.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_STATUS, global::LightSwitchApplication.REF_STATUS.DetailsClass, global::System.Nullable<global::System.DateTime>> CreatedDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties.CreatedDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_STATUS, global::LightSwitchApplication.REF_STATUS.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_STATUS, global::LightSwitchApplication.REF_STATUS.DetailsClass, string> CreatedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties.CreatedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_STATUS, global::LightSwitchApplication.REF_STATUS.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_STATUS, global::LightSwitchApplication.REF_STATUS.DetailsClass, global::System.Nullable<global::System.DateTime>> ModifiedDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties.ModifiedDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_STATUS, global::LightSwitchApplication.REF_STATUS.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_STATUS, global::LightSwitchApplication.REF_STATUS.DetailsClass, string> ModifiedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties.ModifiedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_STATUS, global::LightSwitchApplication.REF_STATUS.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.REF_STATUS, global::LightSwitchApplication.REF_STATUS.DetailsClass, global::LightSwitchApplication.RESOURCE> RESOURCEs
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties.RESOURCEs) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.REF_STATUS, global::LightSwitchApplication.REF_STATUS.DetailsClass, global::LightSwitchApplication.RESOURCE>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new short StatusID { get; }
                new string Name { get; set; }
                new string Description { get; set; }
                new global::System.Nullable<global::System.DateTime> CreatedDate { get; set; }
                new string CreatedBy { get; set; }
                new global::System.Nullable<global::System.DateTime> ModifiedDate { get; set; }
                new string ModifiedBy { get; set; }
                new global::System.Collections.IEnumerable RESOURCEs { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_STATUS, global::LightSwitchApplication.REF_STATUS.DetailsClass, short>.Entry
                    StatusID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_STATUS, global::LightSwitchApplication.REF_STATUS.DetailsClass, short>.Entry(
                        "StatusID",
                        global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties._StatusID_Stub,
                        global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties._StatusID_ComputeIsReadOnly,
                        global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties._StatusID_Validate,
                        global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties._StatusID_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties._StatusID_OnValueChanged);
                private static void _StatusID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.REF_STATUS.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_STATUS, global::LightSwitchApplication.REF_STATUS.DetailsClass, short>.Data> c, global::LightSwitchApplication.REF_STATUS.DetailsClass d, object sf)
                {
                    c(d, ref d._StatusID, sf);
                }
                private static bool _StatusID_ComputeIsReadOnly(global::LightSwitchApplication.REF_STATUS e)
                {
                    bool result = false;
                    e.StatusID_IsReadOnly(ref result);
                    return result;
                }
                private static void _StatusID_Validate(global::LightSwitchApplication.REF_STATUS e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.StatusID_Validate(r);
                }
                private static short _StatusID_GetImplementationValue(global::LightSwitchApplication.REF_STATUS.DetailsClass d)
                {
                    return d.ImplementationEntity.StatusID;
                }
                private static void _StatusID_OnValueChanged(global::LightSwitchApplication.REF_STATUS e)
                {
                    e.StatusID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_STATUS, global::LightSwitchApplication.REF_STATUS.DetailsClass, string>.Entry
                    Name = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_STATUS, global::LightSwitchApplication.REF_STATUS.DetailsClass, string>.Entry(
                        "Name",
                        global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties._Name_Stub,
                        global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties._Name_ComputeIsReadOnly,
                        global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties._Name_Validate,
                        global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties._Name_GetImplementationValue,
                        global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties._Name_SetImplementationValue,
                        global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties._Name_OnValueChanged);
                private static void _Name_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.REF_STATUS.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_STATUS, global::LightSwitchApplication.REF_STATUS.DetailsClass, string>.Data> c, global::LightSwitchApplication.REF_STATUS.DetailsClass d, object sf)
                {
                    c(d, ref d._Name, sf);
                }
                private static bool _Name_ComputeIsReadOnly(global::LightSwitchApplication.REF_STATUS e)
                {
                    bool result = false;
                    e.Name_IsReadOnly(ref result);
                    return result;
                }
                private static void _Name_Validate(global::LightSwitchApplication.REF_STATUS e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Name_Validate(r);
                }
                private static string _Name_GetImplementationValue(global::LightSwitchApplication.REF_STATUS.DetailsClass d)
                {
                    return d.ImplementationEntity.Name;
                }
                private static void _Name_SetImplementationValue(global::LightSwitchApplication.REF_STATUS.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Name = v;
                }
                private static void _Name_OnValueChanged(global::LightSwitchApplication.REF_STATUS e)
                {
                    e.Name_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_STATUS, global::LightSwitchApplication.REF_STATUS.DetailsClass, string>.Entry
                    Description = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_STATUS, global::LightSwitchApplication.REF_STATUS.DetailsClass, string>.Entry(
                        "Description",
                        global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties._Description_Stub,
                        global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties._Description_ComputeIsReadOnly,
                        global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties._Description_Validate,
                        global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties._Description_GetImplementationValue,
                        global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties._Description_SetImplementationValue,
                        global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties._Description_OnValueChanged);
                private static void _Description_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.REF_STATUS.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_STATUS, global::LightSwitchApplication.REF_STATUS.DetailsClass, string>.Data> c, global::LightSwitchApplication.REF_STATUS.DetailsClass d, object sf)
                {
                    c(d, ref d._Description, sf);
                }
                private static bool _Description_ComputeIsReadOnly(global::LightSwitchApplication.REF_STATUS e)
                {
                    bool result = false;
                    e.Description_IsReadOnly(ref result);
                    return result;
                }
                private static void _Description_Validate(global::LightSwitchApplication.REF_STATUS e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Description_Validate(r);
                }
                private static string _Description_GetImplementationValue(global::LightSwitchApplication.REF_STATUS.DetailsClass d)
                {
                    return d.ImplementationEntity.Description;
                }
                private static void _Description_SetImplementationValue(global::LightSwitchApplication.REF_STATUS.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Description = v;
                }
                private static void _Description_OnValueChanged(global::LightSwitchApplication.REF_STATUS e)
                {
                    e.Description_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_STATUS, global::LightSwitchApplication.REF_STATUS.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    CreatedDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_STATUS, global::LightSwitchApplication.REF_STATUS.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "CreatedDate",
                        global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties._CreatedDate_Stub,
                        global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties._CreatedDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties._CreatedDate_Validate,
                        global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties._CreatedDate_GetImplementationValue,
                        global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties._CreatedDate_SetImplementationValue,
                        global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties._CreatedDate_OnValueChanged);
                private static void _CreatedDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.REF_STATUS.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_STATUS, global::LightSwitchApplication.REF_STATUS.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.REF_STATUS.DetailsClass d, object sf)
                {
                    c(d, ref d._CreatedDate, sf);
                }
                private static bool _CreatedDate_ComputeIsReadOnly(global::LightSwitchApplication.REF_STATUS e)
                {
                    bool result = false;
                    e.CreatedDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreatedDate_Validate(global::LightSwitchApplication.REF_STATUS e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreatedDate_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _CreatedDate_GetImplementationValue(global::LightSwitchApplication.REF_STATUS.DetailsClass d)
                {
                    return d.ImplementationEntity.CreatedDate;
                }
                private static void _CreatedDate_SetImplementationValue(global::LightSwitchApplication.REF_STATUS.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.CreatedDate = global::LightSwitchApplication.REF_STATUS.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _CreatedDate_OnValueChanged(global::LightSwitchApplication.REF_STATUS e)
                {
                    e.CreatedDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_STATUS, global::LightSwitchApplication.REF_STATUS.DetailsClass, string>.Entry
                    CreatedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_STATUS, global::LightSwitchApplication.REF_STATUS.DetailsClass, string>.Entry(
                        "CreatedBy",
                        global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties._CreatedBy_Stub,
                        global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties._CreatedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties._CreatedBy_Validate,
                        global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties._CreatedBy_GetImplementationValue,
                        global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties._CreatedBy_SetImplementationValue,
                        global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties._CreatedBy_OnValueChanged);
                private static void _CreatedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.REF_STATUS.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_STATUS, global::LightSwitchApplication.REF_STATUS.DetailsClass, string>.Data> c, global::LightSwitchApplication.REF_STATUS.DetailsClass d, object sf)
                {
                    c(d, ref d._CreatedBy, sf);
                }
                private static bool _CreatedBy_ComputeIsReadOnly(global::LightSwitchApplication.REF_STATUS e)
                {
                    bool result = false;
                    e.CreatedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreatedBy_Validate(global::LightSwitchApplication.REF_STATUS e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreatedBy_Validate(r);
                }
                private static string _CreatedBy_GetImplementationValue(global::LightSwitchApplication.REF_STATUS.DetailsClass d)
                {
                    return d.ImplementationEntity.CreatedBy;
                }
                private static void _CreatedBy_SetImplementationValue(global::LightSwitchApplication.REF_STATUS.DetailsClass d, string v)
                {
                    d.ImplementationEntity.CreatedBy = v;
                }
                private static void _CreatedBy_OnValueChanged(global::LightSwitchApplication.REF_STATUS e)
                {
                    e.CreatedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_STATUS, global::LightSwitchApplication.REF_STATUS.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    ModifiedDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_STATUS, global::LightSwitchApplication.REF_STATUS.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "ModifiedDate",
                        global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties._ModifiedDate_Stub,
                        global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties._ModifiedDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties._ModifiedDate_Validate,
                        global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties._ModifiedDate_GetImplementationValue,
                        global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties._ModifiedDate_SetImplementationValue,
                        global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties._ModifiedDate_OnValueChanged);
                private static void _ModifiedDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.REF_STATUS.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_STATUS, global::LightSwitchApplication.REF_STATUS.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.REF_STATUS.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifiedDate, sf);
                }
                private static bool _ModifiedDate_ComputeIsReadOnly(global::LightSwitchApplication.REF_STATUS e)
                {
                    bool result = false;
                    e.ModifiedDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifiedDate_Validate(global::LightSwitchApplication.REF_STATUS e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifiedDate_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _ModifiedDate_GetImplementationValue(global::LightSwitchApplication.REF_STATUS.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifiedDate;
                }
                private static void _ModifiedDate_SetImplementationValue(global::LightSwitchApplication.REF_STATUS.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.ModifiedDate = global::LightSwitchApplication.REF_STATUS.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _ModifiedDate_OnValueChanged(global::LightSwitchApplication.REF_STATUS e)
                {
                    e.ModifiedDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_STATUS, global::LightSwitchApplication.REF_STATUS.DetailsClass, string>.Entry
                    ModifiedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_STATUS, global::LightSwitchApplication.REF_STATUS.DetailsClass, string>.Entry(
                        "ModifiedBy",
                        global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties._ModifiedBy_Stub,
                        global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties._ModifiedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties._ModifiedBy_Validate,
                        global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties._ModifiedBy_GetImplementationValue,
                        global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties._ModifiedBy_SetImplementationValue,
                        global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties._ModifiedBy_OnValueChanged);
                private static void _ModifiedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.REF_STATUS.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_STATUS, global::LightSwitchApplication.REF_STATUS.DetailsClass, string>.Data> c, global::LightSwitchApplication.REF_STATUS.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifiedBy, sf);
                }
                private static bool _ModifiedBy_ComputeIsReadOnly(global::LightSwitchApplication.REF_STATUS e)
                {
                    bool result = false;
                    e.ModifiedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifiedBy_Validate(global::LightSwitchApplication.REF_STATUS e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifiedBy_Validate(r);
                }
                private static string _ModifiedBy_GetImplementationValue(global::LightSwitchApplication.REF_STATUS.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifiedBy;
                }
                private static void _ModifiedBy_SetImplementationValue(global::LightSwitchApplication.REF_STATUS.DetailsClass d, string v)
                {
                    d.ImplementationEntity.ModifiedBy = v;
                }
                private static void _ModifiedBy_OnValueChanged(global::LightSwitchApplication.REF_STATUS e)
                {
                    e.ModifiedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.REF_STATUS, global::LightSwitchApplication.REF_STATUS.DetailsClass, global::LightSwitchApplication.RESOURCE>.Entry
                    RESOURCEs = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.REF_STATUS, global::LightSwitchApplication.REF_STATUS.DetailsClass, global::LightSwitchApplication.RESOURCE>.Entry(
                        "RESOURCEs",
                        global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties._RESOURCEs_Stub,
                        global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties._RESOURCEs_GetReferencedEntities,
                        global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties._RESOURCEs_GetEntityCollection);
                private static void _RESOURCEs_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.REF_STATUS.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.REF_STATUS, global::LightSwitchApplication.REF_STATUS.DetailsClass, global::LightSwitchApplication.RESOURCE>.Data> c, global::LightSwitchApplication.REF_STATUS.DetailsClass d, object sf)
                {
                    c(d, ref d._RESOURCEs, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.RESOURCE> _RESOURCEs_GetReferencedEntities(global::LightSwitchApplication.REF_STATUS.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass>(global::LightSwitchApplication.REF_STATUS.DetailsClass.PropertySetProperties.RESOURCEs, ref d._RESOURCEs);
                }
                private static global::System.Collections.IEnumerable _RESOURCEs_GetEntityCollection(global::LightSwitchApplication.REF_STATUS.DetailsClass d)
                {
                    return d.ImplementationEntity.RESOURCEs;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_STATUS, global::LightSwitchApplication.REF_STATUS.DetailsClass, short>.Data _StatusID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_STATUS, global::LightSwitchApplication.REF_STATUS.DetailsClass, string>.Data _Name;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_STATUS, global::LightSwitchApplication.REF_STATUS.DetailsClass, string>.Data _Description;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_STATUS, global::LightSwitchApplication.REF_STATUS.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _CreatedDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_STATUS, global::LightSwitchApplication.REF_STATUS.DetailsClass, string>.Data _CreatedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_STATUS, global::LightSwitchApplication.REF_STATUS.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _ModifiedDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_STATUS, global::LightSwitchApplication.REF_STATUS.DetailsClass, string>.Data _ModifiedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.REF_STATUS, global::LightSwitchApplication.REF_STATUS.DetailsClass, global::LightSwitchApplication.RESOURCE>.Data _RESOURCEs;
            
        }
    
        #endregion
    }
    
    #endregion
}
