

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    public sealed partial class TP_STAKEHOLDER : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.TP_STAKEHOLDER, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the TP_STAKEHOLDER entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public TP_STAKEHOLDER()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public TP_STAKEHOLDER(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.TP_STAKEHOLDER> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TP_STAKEHOLDER_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TP_STAKEHOLDER_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int TpStakeholderID
        {
            get
            {
                return global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.GetValue(this, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties.TpStakeholderID);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TpStakeholderID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TpStakeholderID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TpStakeholderID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string CreatedBy
        {
            get
            {
                return global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.GetValue(this, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties.CreatedBy);
            }
            set
            {
                global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.SetValue(this, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties.CreatedBy, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> CreatedDate
        {
            get
            {
                return global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.GetValue(this, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties.CreatedDate);
            }
            set
            {
                global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.SetValue(this, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties.CreatedDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedDate_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ModifiedBy
        {
            get
            {
                return global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.GetValue(this, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties.ModifiedBy);
            }
            set
            {
                global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.SetValue(this, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties.ModifiedBy, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> ModifiedDate
        {
            get
            {
                return global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.GetValue(this, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties.ModifiedDate);
            }
            set
            {
                global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.SetValue(this, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties.ModifiedDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedDate_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.REF_STAKEHOLDER REF_STAKEHOLDER
        {
            get
            {
                return global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.GetValue(this, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties.REF_STAKEHOLDER);
            }
            set
            {
                global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.SetValue(this, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties.REF_STAKEHOLDER, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void REF_STAKEHOLDER_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void REF_STAKEHOLDER_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void REF_STAKEHOLDER_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.TP TP
        {
            get
            {
                return global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.GetValue(this, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties.TP);
            }
            set
            {
                global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.SetValue(this, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties.TP, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TP_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TP_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TP_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.TP_STAKEHOLDER,
                global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass,
                global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.IImplementation,
                global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.TP_STAKEHOLDER, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.TP_STAKEHOLDER, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties.TpStakeholderID;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.TP_STAKEHOLDER, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass>.Entry
                __TP_STAKEHOLDEREntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.TP_STAKEHOLDER, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass>.Entry(
                    global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.__TP_STAKEHOLDER_CreateNew,
                    global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.__TP_STAKEHOLDER_Created,
                    global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.__TP_STAKEHOLDER_AllowSaveWithErrors);
            private static global::LightSwitchApplication.TP_STAKEHOLDER __TP_STAKEHOLDER_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.TP_STAKEHOLDER> es)
            {
                return new global::LightSwitchApplication.TP_STAKEHOLDER(es);
            }
            private static void __TP_STAKEHOLDER_Created(global::LightSwitchApplication.TP_STAKEHOLDER e)
            {
                e.TP_STAKEHOLDER_Created();
            }
            private static bool __TP_STAKEHOLDER_AllowSaveWithErrors(global::LightSwitchApplication.TP_STAKEHOLDER e)
            {
                bool result = false;
                e.TP_STAKEHOLDER_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.TP_STAKEHOLDER, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.TP_STAKEHOLDER, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.TP_STAKEHOLDER, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_STAKEHOLDER, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass, int> TpStakeholderID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties.TpStakeholderID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_STAKEHOLDER, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_STAKEHOLDER, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass, string> CreatedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties.CreatedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_STAKEHOLDER, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_STAKEHOLDER, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass, global::System.Nullable<global::System.DateTime>> CreatedDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties.CreatedDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_STAKEHOLDER, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_STAKEHOLDER, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass, string> ModifiedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties.ModifiedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_STAKEHOLDER, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_STAKEHOLDER, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass, global::System.Nullable<global::System.DateTime>> ModifiedDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties.ModifiedDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_STAKEHOLDER, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.TP_STAKEHOLDER, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass, global::LightSwitchApplication.REF_STAKEHOLDER> REF_STAKEHOLDER
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties.REF_STAKEHOLDER) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.TP_STAKEHOLDER, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass, global::LightSwitchApplication.REF_STAKEHOLDER>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.TP_STAKEHOLDER, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass, global::LightSwitchApplication.TP> TP
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties.TP) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.TP_STAKEHOLDER, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass, global::LightSwitchApplication.TP>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int TpStakeholderID { get; }
                new string CreatedBy { get; set; }
                new global::System.Nullable<global::System.DateTime> CreatedDate { get; set; }
                new string ModifiedBy { get; set; }
                new global::System.Nullable<global::System.DateTime> ModifiedDate { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation REF_STAKEHOLDER { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation TP { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_STAKEHOLDER, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass, int>.Entry
                    TpStakeholderID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_STAKEHOLDER, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass, int>.Entry(
                        "TpStakeholderID",
                        global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties._TpStakeholderID_Stub,
                        global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties._TpStakeholderID_ComputeIsReadOnly,
                        global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties._TpStakeholderID_Validate,
                        global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties._TpStakeholderID_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties._TpStakeholderID_OnValueChanged);
                private static void _TpStakeholderID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_STAKEHOLDER, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass, int>.Data> c, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass d, object sf)
                {
                    c(d, ref d._TpStakeholderID, sf);
                }
                private static bool _TpStakeholderID_ComputeIsReadOnly(global::LightSwitchApplication.TP_STAKEHOLDER e)
                {
                    bool result = false;
                    e.TpStakeholderID_IsReadOnly(ref result);
                    return result;
                }
                private static void _TpStakeholderID_Validate(global::LightSwitchApplication.TP_STAKEHOLDER e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.TpStakeholderID_Validate(r);
                }
                private static int _TpStakeholderID_GetImplementationValue(global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass d)
                {
                    return d.ImplementationEntity.TpStakeholderID;
                }
                private static void _TpStakeholderID_OnValueChanged(global::LightSwitchApplication.TP_STAKEHOLDER e)
                {
                    e.TpStakeholderID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_STAKEHOLDER, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass, string>.Entry
                    CreatedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_STAKEHOLDER, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass, string>.Entry(
                        "CreatedBy",
                        global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties._CreatedBy_Stub,
                        global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties._CreatedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties._CreatedBy_Validate,
                        global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties._CreatedBy_GetImplementationValue,
                        global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties._CreatedBy_SetImplementationValue,
                        global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties._CreatedBy_OnValueChanged);
                private static void _CreatedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_STAKEHOLDER, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass, string>.Data> c, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass d, object sf)
                {
                    c(d, ref d._CreatedBy, sf);
                }
                private static bool _CreatedBy_ComputeIsReadOnly(global::LightSwitchApplication.TP_STAKEHOLDER e)
                {
                    bool result = false;
                    e.CreatedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreatedBy_Validate(global::LightSwitchApplication.TP_STAKEHOLDER e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreatedBy_Validate(r);
                }
                private static string _CreatedBy_GetImplementationValue(global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass d)
                {
                    return d.ImplementationEntity.CreatedBy;
                }
                private static void _CreatedBy_SetImplementationValue(global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass d, string v)
                {
                    d.ImplementationEntity.CreatedBy = v;
                }
                private static void _CreatedBy_OnValueChanged(global::LightSwitchApplication.TP_STAKEHOLDER e)
                {
                    e.CreatedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_STAKEHOLDER, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    CreatedDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_STAKEHOLDER, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "CreatedDate",
                        global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties._CreatedDate_Stub,
                        global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties._CreatedDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties._CreatedDate_Validate,
                        global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties._CreatedDate_GetImplementationValue,
                        global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties._CreatedDate_SetImplementationValue,
                        global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties._CreatedDate_OnValueChanged);
                private static void _CreatedDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_STAKEHOLDER, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass d, object sf)
                {
                    c(d, ref d._CreatedDate, sf);
                }
                private static bool _CreatedDate_ComputeIsReadOnly(global::LightSwitchApplication.TP_STAKEHOLDER e)
                {
                    bool result = false;
                    e.CreatedDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreatedDate_Validate(global::LightSwitchApplication.TP_STAKEHOLDER e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreatedDate_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _CreatedDate_GetImplementationValue(global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass d)
                {
                    return d.ImplementationEntity.CreatedDate;
                }
                private static void _CreatedDate_SetImplementationValue(global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.CreatedDate = global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _CreatedDate_OnValueChanged(global::LightSwitchApplication.TP_STAKEHOLDER e)
                {
                    e.CreatedDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_STAKEHOLDER, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass, string>.Entry
                    ModifiedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_STAKEHOLDER, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass, string>.Entry(
                        "ModifiedBy",
                        global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties._ModifiedBy_Stub,
                        global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties._ModifiedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties._ModifiedBy_Validate,
                        global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties._ModifiedBy_GetImplementationValue,
                        global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties._ModifiedBy_SetImplementationValue,
                        global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties._ModifiedBy_OnValueChanged);
                private static void _ModifiedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_STAKEHOLDER, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass, string>.Data> c, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifiedBy, sf);
                }
                private static bool _ModifiedBy_ComputeIsReadOnly(global::LightSwitchApplication.TP_STAKEHOLDER e)
                {
                    bool result = false;
                    e.ModifiedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifiedBy_Validate(global::LightSwitchApplication.TP_STAKEHOLDER e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifiedBy_Validate(r);
                }
                private static string _ModifiedBy_GetImplementationValue(global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifiedBy;
                }
                private static void _ModifiedBy_SetImplementationValue(global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass d, string v)
                {
                    d.ImplementationEntity.ModifiedBy = v;
                }
                private static void _ModifiedBy_OnValueChanged(global::LightSwitchApplication.TP_STAKEHOLDER e)
                {
                    e.ModifiedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_STAKEHOLDER, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    ModifiedDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_STAKEHOLDER, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "ModifiedDate",
                        global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties._ModifiedDate_Stub,
                        global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties._ModifiedDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties._ModifiedDate_Validate,
                        global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties._ModifiedDate_GetImplementationValue,
                        global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties._ModifiedDate_SetImplementationValue,
                        global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties._ModifiedDate_OnValueChanged);
                private static void _ModifiedDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_STAKEHOLDER, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifiedDate, sf);
                }
                private static bool _ModifiedDate_ComputeIsReadOnly(global::LightSwitchApplication.TP_STAKEHOLDER e)
                {
                    bool result = false;
                    e.ModifiedDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifiedDate_Validate(global::LightSwitchApplication.TP_STAKEHOLDER e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifiedDate_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _ModifiedDate_GetImplementationValue(global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifiedDate;
                }
                private static void _ModifiedDate_SetImplementationValue(global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.ModifiedDate = global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _ModifiedDate_OnValueChanged(global::LightSwitchApplication.TP_STAKEHOLDER e)
                {
                    e.ModifiedDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.TP_STAKEHOLDER, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass, global::LightSwitchApplication.REF_STAKEHOLDER>.Entry
                    REF_STAKEHOLDER = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.TP_STAKEHOLDER, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass, global::LightSwitchApplication.REF_STAKEHOLDER>.Entry(
                        "REF_STAKEHOLDER",
                        global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties._REF_STAKEHOLDER_Stub,
                        global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties._REF_STAKEHOLDER_ComputeIsReadOnly,
                        global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties._REF_STAKEHOLDER_Validate,
                        global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties._REF_STAKEHOLDER_GetCoreImplementationValue,
                        global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties._REF_STAKEHOLDER_GetImplementationValue,
                        global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties._REF_STAKEHOLDER_SetImplementationValue,
                        global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties._REF_STAKEHOLDER_Refresh,
                        global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties._REF_STAKEHOLDER_OnValueChanged);
                private static void _REF_STAKEHOLDER_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.TP_STAKEHOLDER, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass, global::LightSwitchApplication.REF_STAKEHOLDER>.Data> c, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass d, object sf)
                {
                    c(d, ref d._REF_STAKEHOLDER, sf);
                }
                private static bool _REF_STAKEHOLDER_ComputeIsReadOnly(global::LightSwitchApplication.TP_STAKEHOLDER e)
                {
                    bool result = false;
                    e.REF_STAKEHOLDER_IsReadOnly(ref result);
                    return result;
                }
                private static void _REF_STAKEHOLDER_Validate(global::LightSwitchApplication.TP_STAKEHOLDER e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.REF_STAKEHOLDER_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _REF_STAKEHOLDER_GetCoreImplementationValue(global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass d)
                {
                    return d.ImplementationEntity.REF_STAKEHOLDER;
                }
                private static global::LightSwitchApplication.REF_STAKEHOLDER _REF_STAKEHOLDER_GetImplementationValue(global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.REF_STAKEHOLDER, global::LightSwitchApplication.REF_STAKEHOLDER.DetailsClass>(global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties.REF_STAKEHOLDER, ref d._REF_STAKEHOLDER);
                }
                private static void _REF_STAKEHOLDER_SetImplementationValue(global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass d, global::LightSwitchApplication.REF_STAKEHOLDER v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties.REF_STAKEHOLDER, ref d._REF_STAKEHOLDER, (i, ev) => i.REF_STAKEHOLDER = ev, v);
                }
                private static void _REF_STAKEHOLDER_Refresh(global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties.REF_STAKEHOLDER, ref d._REF_STAKEHOLDER);
                }
                private static void _REF_STAKEHOLDER_OnValueChanged(global::LightSwitchApplication.TP_STAKEHOLDER e)
                {
                    e.REF_STAKEHOLDER_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.TP_STAKEHOLDER, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass, global::LightSwitchApplication.TP>.Entry
                    TP = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.TP_STAKEHOLDER, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass, global::LightSwitchApplication.TP>.Entry(
                        "TP",
                        global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties._TP_Stub,
                        global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties._TP_ComputeIsReadOnly,
                        global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties._TP_Validate,
                        global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties._TP_GetCoreImplementationValue,
                        global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties._TP_GetImplementationValue,
                        global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties._TP_SetImplementationValue,
                        global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties._TP_Refresh,
                        global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties._TP_OnValueChanged);
                private static void _TP_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.TP_STAKEHOLDER, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass, global::LightSwitchApplication.TP>.Data> c, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass d, object sf)
                {
                    c(d, ref d._TP, sf);
                }
                private static bool _TP_ComputeIsReadOnly(global::LightSwitchApplication.TP_STAKEHOLDER e)
                {
                    bool result = false;
                    e.TP_IsReadOnly(ref result);
                    return result;
                }
                private static void _TP_Validate(global::LightSwitchApplication.TP_STAKEHOLDER e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.TP_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _TP_GetCoreImplementationValue(global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass d)
                {
                    return d.ImplementationEntity.TP;
                }
                private static global::LightSwitchApplication.TP _TP_GetImplementationValue(global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.TP, global::LightSwitchApplication.TP.DetailsClass>(global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties.TP, ref d._TP);
                }
                private static void _TP_SetImplementationValue(global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass d, global::LightSwitchApplication.TP v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties.TP, ref d._TP, (i, ev) => i.TP = ev, v);
                }
                private static void _TP_Refresh(global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.PropertySetProperties.TP, ref d._TP);
                }
                private static void _TP_OnValueChanged(global::LightSwitchApplication.TP_STAKEHOLDER e)
                {
                    e.TP_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_STAKEHOLDER, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass, int>.Data _TpStakeholderID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_STAKEHOLDER, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass, string>.Data _CreatedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_STAKEHOLDER, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _CreatedDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_STAKEHOLDER, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass, string>.Data _ModifiedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_STAKEHOLDER, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _ModifiedDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.TP_STAKEHOLDER, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass, global::LightSwitchApplication.REF_STAKEHOLDER>.Data _REF_STAKEHOLDER;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.TP_STAKEHOLDER, global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass, global::LightSwitchApplication.TP>.Data _TP;
            
        }
    
        #endregion
    }
    
    #endregion
}
