

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    public sealed partial class TP_DOCUMENT_LINK : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the TP_DOCUMENT_LINK entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public TP_DOCUMENT_LINK()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public TP_DOCUMENT_LINK(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.TP_DOCUMENT_LINK> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TP_DOCUMENT_LINK_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TP_DOCUMENT_LINK_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int TpDocumentLinkID
        {
            get
            {
                return global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.GetValue(this, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties.TpDocumentLinkID);
            }
            set
            {
                global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.SetValue(this, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties.TpDocumentLinkID, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TpDocumentLinkID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TpDocumentLinkID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TpDocumentLinkID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Name
        {
            get
            {
                return global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.GetValue(this, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties.Name);
            }
            set
            {
                global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.SetValue(this, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties.Name, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Description
        {
            get
            {
                return global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.GetValue(this, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties.Description);
            }
            set
            {
                global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.SetValue(this, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties.Description, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string CreatedBy
        {
            get
            {
                return global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.GetValue(this, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties.CreatedBy);
            }
            set
            {
                global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.SetValue(this, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties.CreatedBy, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> CreatedDate
        {
            get
            {
                return global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.GetValue(this, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties.CreatedDate);
            }
            set
            {
                global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.SetValue(this, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties.CreatedDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedDate_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Link
        {
            get
            {
                return global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.GetValue(this, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties.Link);
            }
            set
            {
                global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.SetValue(this, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties.Link, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Link_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Link_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Link_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ModifiedBy
        {
            get
            {
                return global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.GetValue(this, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties.ModifiedBy);
            }
            set
            {
                global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.SetValue(this, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties.ModifiedBy, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> ModifiedDate
        {
            get
            {
                return global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.GetValue(this, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties.ModifiedDate);
            }
            set
            {
                global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.SetValue(this, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties.ModifiedDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedDate_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.REF_DOCUMENT_TYPE REF_DOCUMENT_TYPE
        {
            get
            {
                return global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.GetValue(this, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties.REF_DOCUMENT_TYPE);
            }
            set
            {
                global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.SetValue(this, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties.REF_DOCUMENT_TYPE, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void REF_DOCUMENT_TYPE_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void REF_DOCUMENT_TYPE_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void REF_DOCUMENT_TYPE_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.TP TP
        {
            get
            {
                return global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.GetValue(this, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties.TP);
            }
            set
            {
                global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.SetValue(this, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties.TP, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TP_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TP_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TP_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.TP_DOCUMENT_LINK,
                global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass,
                global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.IImplementation,
                global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties.TpDocumentLinkID;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass>.Entry
                __TP_DOCUMENT_LINKEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass>.Entry(
                    global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.__TP_DOCUMENT_LINK_CreateNew,
                    global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.__TP_DOCUMENT_LINK_Created,
                    global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.__TP_DOCUMENT_LINK_AllowSaveWithErrors);
            private static global::LightSwitchApplication.TP_DOCUMENT_LINK __TP_DOCUMENT_LINK_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.TP_DOCUMENT_LINK> es)
            {
                return new global::LightSwitchApplication.TP_DOCUMENT_LINK(es);
            }
            private static void __TP_DOCUMENT_LINK_Created(global::LightSwitchApplication.TP_DOCUMENT_LINK e)
            {
                e.TP_DOCUMENT_LINK_Created();
            }
            private static bool __TP_DOCUMENT_LINK_AllowSaveWithErrors(global::LightSwitchApplication.TP_DOCUMENT_LINK e)
            {
                bool result = false;
                e.TP_DOCUMENT_LINK_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, int> TpDocumentLinkID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties.TpDocumentLinkID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, string> Name
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties.Name) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, string> Description
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties.Description) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, string> CreatedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties.CreatedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, global::System.Nullable<global::System.DateTime>> CreatedDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties.CreatedDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, string> Link
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties.Link) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, string> ModifiedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties.ModifiedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, global::System.Nullable<global::System.DateTime>> ModifiedDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties.ModifiedDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, global::LightSwitchApplication.REF_DOCUMENT_TYPE> REF_DOCUMENT_TYPE
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties.REF_DOCUMENT_TYPE) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, global::LightSwitchApplication.REF_DOCUMENT_TYPE>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, global::LightSwitchApplication.TP> TP
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties.TP) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, global::LightSwitchApplication.TP>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int TpDocumentLinkID { get; set; }
                new string Name { get; set; }
                new string Description { get; set; }
                new string CreatedBy { get; set; }
                new global::System.Nullable<global::System.DateTime> CreatedDate { get; set; }
                new string Link { get; set; }
                new string ModifiedBy { get; set; }
                new global::System.Nullable<global::System.DateTime> ModifiedDate { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation REF_DOCUMENT_TYPE { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation TP { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, int>.Entry
                    TpDocumentLinkID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, int>.Entry(
                        "TpDocumentLinkID",
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._TpDocumentLinkID_Stub,
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._TpDocumentLinkID_ComputeIsReadOnly,
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._TpDocumentLinkID_Validate,
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._TpDocumentLinkID_GetImplementationValue,
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._TpDocumentLinkID_SetImplementationValue,
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._TpDocumentLinkID_OnValueChanged);
                private static void _TpDocumentLinkID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, int>.Data> c, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass d, object sf)
                {
                    c(d, ref d._TpDocumentLinkID, sf);
                }
                private static bool _TpDocumentLinkID_ComputeIsReadOnly(global::LightSwitchApplication.TP_DOCUMENT_LINK e)
                {
                    bool result = false;
                    e.TpDocumentLinkID_IsReadOnly(ref result);
                    return result;
                }
                private static void _TpDocumentLinkID_Validate(global::LightSwitchApplication.TP_DOCUMENT_LINK e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.TpDocumentLinkID_Validate(r);
                }
                private static int _TpDocumentLinkID_GetImplementationValue(global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass d)
                {
                    return d.ImplementationEntity.TpDocumentLinkID;
                }
                private static void _TpDocumentLinkID_SetImplementationValue(global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass d, int v)
                {
                    d.ImplementationEntity.TpDocumentLinkID = v;
                }
                private static void _TpDocumentLinkID_OnValueChanged(global::LightSwitchApplication.TP_DOCUMENT_LINK e)
                {
                    e.TpDocumentLinkID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, string>.Entry
                    Name = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, string>.Entry(
                        "Name",
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._Name_Stub,
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._Name_ComputeIsReadOnly,
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._Name_Validate,
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._Name_GetImplementationValue,
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._Name_SetImplementationValue,
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._Name_OnValueChanged);
                private static void _Name_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, string>.Data> c, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass d, object sf)
                {
                    c(d, ref d._Name, sf);
                }
                private static bool _Name_ComputeIsReadOnly(global::LightSwitchApplication.TP_DOCUMENT_LINK e)
                {
                    bool result = false;
                    e.Name_IsReadOnly(ref result);
                    return result;
                }
                private static void _Name_Validate(global::LightSwitchApplication.TP_DOCUMENT_LINK e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Name_Validate(r);
                }
                private static string _Name_GetImplementationValue(global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass d)
                {
                    return d.ImplementationEntity.Name;
                }
                private static void _Name_SetImplementationValue(global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Name = v;
                }
                private static void _Name_OnValueChanged(global::LightSwitchApplication.TP_DOCUMENT_LINK e)
                {
                    e.Name_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, string>.Entry
                    Description = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, string>.Entry(
                        "Description",
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._Description_Stub,
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._Description_ComputeIsReadOnly,
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._Description_Validate,
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._Description_GetImplementationValue,
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._Description_SetImplementationValue,
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._Description_OnValueChanged);
                private static void _Description_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, string>.Data> c, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass d, object sf)
                {
                    c(d, ref d._Description, sf);
                }
                private static bool _Description_ComputeIsReadOnly(global::LightSwitchApplication.TP_DOCUMENT_LINK e)
                {
                    bool result = false;
                    e.Description_IsReadOnly(ref result);
                    return result;
                }
                private static void _Description_Validate(global::LightSwitchApplication.TP_DOCUMENT_LINK e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Description_Validate(r);
                }
                private static string _Description_GetImplementationValue(global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass d)
                {
                    return d.ImplementationEntity.Description;
                }
                private static void _Description_SetImplementationValue(global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Description = v;
                }
                private static void _Description_OnValueChanged(global::LightSwitchApplication.TP_DOCUMENT_LINK e)
                {
                    e.Description_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, string>.Entry
                    CreatedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, string>.Entry(
                        "CreatedBy",
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._CreatedBy_Stub,
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._CreatedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._CreatedBy_Validate,
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._CreatedBy_GetImplementationValue,
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._CreatedBy_SetImplementationValue,
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._CreatedBy_OnValueChanged);
                private static void _CreatedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, string>.Data> c, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass d, object sf)
                {
                    c(d, ref d._CreatedBy, sf);
                }
                private static bool _CreatedBy_ComputeIsReadOnly(global::LightSwitchApplication.TP_DOCUMENT_LINK e)
                {
                    bool result = false;
                    e.CreatedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreatedBy_Validate(global::LightSwitchApplication.TP_DOCUMENT_LINK e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreatedBy_Validate(r);
                }
                private static string _CreatedBy_GetImplementationValue(global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass d)
                {
                    return d.ImplementationEntity.CreatedBy;
                }
                private static void _CreatedBy_SetImplementationValue(global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass d, string v)
                {
                    d.ImplementationEntity.CreatedBy = v;
                }
                private static void _CreatedBy_OnValueChanged(global::LightSwitchApplication.TP_DOCUMENT_LINK e)
                {
                    e.CreatedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    CreatedDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "CreatedDate",
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._CreatedDate_Stub,
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._CreatedDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._CreatedDate_Validate,
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._CreatedDate_GetImplementationValue,
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._CreatedDate_SetImplementationValue,
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._CreatedDate_OnValueChanged);
                private static void _CreatedDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass d, object sf)
                {
                    c(d, ref d._CreatedDate, sf);
                }
                private static bool _CreatedDate_ComputeIsReadOnly(global::LightSwitchApplication.TP_DOCUMENT_LINK e)
                {
                    bool result = false;
                    e.CreatedDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreatedDate_Validate(global::LightSwitchApplication.TP_DOCUMENT_LINK e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreatedDate_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _CreatedDate_GetImplementationValue(global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass d)
                {
                    return d.ImplementationEntity.CreatedDate;
                }
                private static void _CreatedDate_SetImplementationValue(global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.CreatedDate = global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _CreatedDate_OnValueChanged(global::LightSwitchApplication.TP_DOCUMENT_LINK e)
                {
                    e.CreatedDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, string>.Entry
                    Link = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, string>.Entry(
                        "Link",
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._Link_Stub,
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._Link_ComputeIsReadOnly,
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._Link_Validate,
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._Link_GetImplementationValue,
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._Link_SetImplementationValue,
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._Link_OnValueChanged);
                private static void _Link_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, string>.Data> c, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass d, object sf)
                {
                    c(d, ref d._Link, sf);
                }
                private static bool _Link_ComputeIsReadOnly(global::LightSwitchApplication.TP_DOCUMENT_LINK e)
                {
                    bool result = false;
                    e.Link_IsReadOnly(ref result);
                    return result;
                }
                private static void _Link_Validate(global::LightSwitchApplication.TP_DOCUMENT_LINK e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Link_Validate(r);
                }
                private static string _Link_GetImplementationValue(global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass d)
                {
                    return d.ImplementationEntity.Link;
                }
                private static void _Link_SetImplementationValue(global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Link = v;
                }
                private static void _Link_OnValueChanged(global::LightSwitchApplication.TP_DOCUMENT_LINK e)
                {
                    e.Link_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, string>.Entry
                    ModifiedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, string>.Entry(
                        "ModifiedBy",
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._ModifiedBy_Stub,
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._ModifiedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._ModifiedBy_Validate,
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._ModifiedBy_GetImplementationValue,
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._ModifiedBy_SetImplementationValue,
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._ModifiedBy_OnValueChanged);
                private static void _ModifiedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, string>.Data> c, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifiedBy, sf);
                }
                private static bool _ModifiedBy_ComputeIsReadOnly(global::LightSwitchApplication.TP_DOCUMENT_LINK e)
                {
                    bool result = false;
                    e.ModifiedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifiedBy_Validate(global::LightSwitchApplication.TP_DOCUMENT_LINK e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifiedBy_Validate(r);
                }
                private static string _ModifiedBy_GetImplementationValue(global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifiedBy;
                }
                private static void _ModifiedBy_SetImplementationValue(global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass d, string v)
                {
                    d.ImplementationEntity.ModifiedBy = v;
                }
                private static void _ModifiedBy_OnValueChanged(global::LightSwitchApplication.TP_DOCUMENT_LINK e)
                {
                    e.ModifiedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    ModifiedDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "ModifiedDate",
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._ModifiedDate_Stub,
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._ModifiedDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._ModifiedDate_Validate,
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._ModifiedDate_GetImplementationValue,
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._ModifiedDate_SetImplementationValue,
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._ModifiedDate_OnValueChanged);
                private static void _ModifiedDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifiedDate, sf);
                }
                private static bool _ModifiedDate_ComputeIsReadOnly(global::LightSwitchApplication.TP_DOCUMENT_LINK e)
                {
                    bool result = false;
                    e.ModifiedDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifiedDate_Validate(global::LightSwitchApplication.TP_DOCUMENT_LINK e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifiedDate_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _ModifiedDate_GetImplementationValue(global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifiedDate;
                }
                private static void _ModifiedDate_SetImplementationValue(global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.ModifiedDate = global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _ModifiedDate_OnValueChanged(global::LightSwitchApplication.TP_DOCUMENT_LINK e)
                {
                    e.ModifiedDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, global::LightSwitchApplication.REF_DOCUMENT_TYPE>.Entry
                    REF_DOCUMENT_TYPE = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, global::LightSwitchApplication.REF_DOCUMENT_TYPE>.Entry(
                        "REF_DOCUMENT_TYPE",
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._REF_DOCUMENT_TYPE_Stub,
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._REF_DOCUMENT_TYPE_ComputeIsReadOnly,
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._REF_DOCUMENT_TYPE_Validate,
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._REF_DOCUMENT_TYPE_GetCoreImplementationValue,
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._REF_DOCUMENT_TYPE_GetImplementationValue,
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._REF_DOCUMENT_TYPE_SetImplementationValue,
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._REF_DOCUMENT_TYPE_Refresh,
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._REF_DOCUMENT_TYPE_OnValueChanged);
                private static void _REF_DOCUMENT_TYPE_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, global::LightSwitchApplication.REF_DOCUMENT_TYPE>.Data> c, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass d, object sf)
                {
                    c(d, ref d._REF_DOCUMENT_TYPE, sf);
                }
                private static bool _REF_DOCUMENT_TYPE_ComputeIsReadOnly(global::LightSwitchApplication.TP_DOCUMENT_LINK e)
                {
                    bool result = false;
                    e.REF_DOCUMENT_TYPE_IsReadOnly(ref result);
                    return result;
                }
                private static void _REF_DOCUMENT_TYPE_Validate(global::LightSwitchApplication.TP_DOCUMENT_LINK e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.REF_DOCUMENT_TYPE_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _REF_DOCUMENT_TYPE_GetCoreImplementationValue(global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass d)
                {
                    return d.ImplementationEntity.REF_DOCUMENT_TYPE;
                }
                private static global::LightSwitchApplication.REF_DOCUMENT_TYPE _REF_DOCUMENT_TYPE_GetImplementationValue(global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.REF_DOCUMENT_TYPE, global::LightSwitchApplication.REF_DOCUMENT_TYPE.DetailsClass>(global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties.REF_DOCUMENT_TYPE, ref d._REF_DOCUMENT_TYPE);
                }
                private static void _REF_DOCUMENT_TYPE_SetImplementationValue(global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass d, global::LightSwitchApplication.REF_DOCUMENT_TYPE v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties.REF_DOCUMENT_TYPE, ref d._REF_DOCUMENT_TYPE, (i, ev) => i.REF_DOCUMENT_TYPE = ev, v);
                }
                private static void _REF_DOCUMENT_TYPE_Refresh(global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties.REF_DOCUMENT_TYPE, ref d._REF_DOCUMENT_TYPE);
                }
                private static void _REF_DOCUMENT_TYPE_OnValueChanged(global::LightSwitchApplication.TP_DOCUMENT_LINK e)
                {
                    e.REF_DOCUMENT_TYPE_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, global::LightSwitchApplication.TP>.Entry
                    TP = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, global::LightSwitchApplication.TP>.Entry(
                        "TP",
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._TP_Stub,
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._TP_ComputeIsReadOnly,
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._TP_Validate,
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._TP_GetCoreImplementationValue,
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._TP_GetImplementationValue,
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._TP_SetImplementationValue,
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._TP_Refresh,
                        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties._TP_OnValueChanged);
                private static void _TP_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, global::LightSwitchApplication.TP>.Data> c, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass d, object sf)
                {
                    c(d, ref d._TP, sf);
                }
                private static bool _TP_ComputeIsReadOnly(global::LightSwitchApplication.TP_DOCUMENT_LINK e)
                {
                    bool result = false;
                    e.TP_IsReadOnly(ref result);
                    return result;
                }
                private static void _TP_Validate(global::LightSwitchApplication.TP_DOCUMENT_LINK e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.TP_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _TP_GetCoreImplementationValue(global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass d)
                {
                    return d.ImplementationEntity.TP;
                }
                private static global::LightSwitchApplication.TP _TP_GetImplementationValue(global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.TP, global::LightSwitchApplication.TP.DetailsClass>(global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties.TP, ref d._TP);
                }
                private static void _TP_SetImplementationValue(global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass d, global::LightSwitchApplication.TP v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties.TP, ref d._TP, (i, ev) => i.TP = ev, v);
                }
                private static void _TP_Refresh(global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.PropertySetProperties.TP, ref d._TP);
                }
                private static void _TP_OnValueChanged(global::LightSwitchApplication.TP_DOCUMENT_LINK e)
                {
                    e.TP_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, int>.Data _TpDocumentLinkID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, string>.Data _Name;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, string>.Data _Description;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, string>.Data _CreatedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _CreatedDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, string>.Data _Link;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, string>.Data _ModifiedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _ModifiedDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, global::LightSwitchApplication.REF_DOCUMENT_TYPE>.Data _REF_DOCUMENT_TYPE;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.TP_DOCUMENT_LINK, global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass, global::LightSwitchApplication.TP>.Data _TP;
            
        }
    
        #endregion
    }
    
    #endregion
}
