

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    public sealed partial class REF_PHASE : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.REF_PHASE, global::LightSwitchApplication.REF_PHASE.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the REF_PHASE entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public REF_PHASE()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public REF_PHASE(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.REF_PHASE> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.REF_PHASE.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void REF_PHASE_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void REF_PHASE_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public short PhaseID
        {
            get
            {
                return global::LightSwitchApplication.REF_PHASE.DetailsClass.GetValue(this, global::LightSwitchApplication.REF_PHASE.DetailsClass.PropertySetProperties.PhaseID);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PhaseID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PhaseID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PhaseID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Name
        {
            get
            {
                return global::LightSwitchApplication.REF_PHASE.DetailsClass.GetValue(this, global::LightSwitchApplication.REF_PHASE.DetailsClass.PropertySetProperties.Name);
            }
            set
            {
                global::LightSwitchApplication.REF_PHASE.DetailsClass.SetValue(this, global::LightSwitchApplication.REF_PHASE.DetailsClass.PropertySetProperties.Name, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Description
        {
            get
            {
                return global::LightSwitchApplication.REF_PHASE.DetailsClass.GetValue(this, global::LightSwitchApplication.REF_PHASE.DetailsClass.PropertySetProperties.Description);
            }
            set
            {
                global::LightSwitchApplication.REF_PHASE.DetailsClass.SetValue(this, global::LightSwitchApplication.REF_PHASE.DetailsClass.PropertySetProperties.Description, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> CreatedDate
        {
            get
            {
                return global::LightSwitchApplication.REF_PHASE.DetailsClass.GetValue(this, global::LightSwitchApplication.REF_PHASE.DetailsClass.PropertySetProperties.CreatedDate);
            }
            set
            {
                global::LightSwitchApplication.REF_PHASE.DetailsClass.SetValue(this, global::LightSwitchApplication.REF_PHASE.DetailsClass.PropertySetProperties.CreatedDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedDate_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string CreatedBy
        {
            get
            {
                return global::LightSwitchApplication.REF_PHASE.DetailsClass.GetValue(this, global::LightSwitchApplication.REF_PHASE.DetailsClass.PropertySetProperties.CreatedBy);
            }
            set
            {
                global::LightSwitchApplication.REF_PHASE.DetailsClass.SetValue(this, global::LightSwitchApplication.REF_PHASE.DetailsClass.PropertySetProperties.CreatedBy, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.TP_PHASE> TP_PHASEs
        {
            get
            {
                return global::LightSwitchApplication.REF_PHASE.DetailsClass.GetValue(this, global::LightSwitchApplication.REF_PHASE.DetailsClass.PropertySetProperties.TP_PHASEs);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.TP_PHASE> TP_PHASEsQuery
        {
            get
            {
                return global::LightSwitchApplication.REF_PHASE.DetailsClass.GetQuery(this, global::LightSwitchApplication.REF_PHASE.DetailsClass.PropertySetProperties.TP_PHASEs);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.REF_PHASE,
                global::LightSwitchApplication.REF_PHASE.DetailsClass,
                global::LightSwitchApplication.REF_PHASE.DetailsClass.IImplementation,
                global::LightSwitchApplication.REF_PHASE.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.REF_PHASE, global::LightSwitchApplication.REF_PHASE.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.REF_PHASE, global::LightSwitchApplication.REF_PHASE.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.REF_PHASE.DetailsClass.PropertySetProperties.PhaseID;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.REF_PHASE, global::LightSwitchApplication.REF_PHASE.DetailsClass>.Entry
                __REF_PHASEEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.REF_PHASE, global::LightSwitchApplication.REF_PHASE.DetailsClass>.Entry(
                    global::LightSwitchApplication.REF_PHASE.DetailsClass.__REF_PHASE_CreateNew,
                    global::LightSwitchApplication.REF_PHASE.DetailsClass.__REF_PHASE_Created,
                    global::LightSwitchApplication.REF_PHASE.DetailsClass.__REF_PHASE_AllowSaveWithErrors);
            private static global::LightSwitchApplication.REF_PHASE __REF_PHASE_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.REF_PHASE> es)
            {
                return new global::LightSwitchApplication.REF_PHASE(es);
            }
            private static void __REF_PHASE_Created(global::LightSwitchApplication.REF_PHASE e)
            {
                e.REF_PHASE_Created();
            }
            private static bool __REF_PHASE_AllowSaveWithErrors(global::LightSwitchApplication.REF_PHASE e)
            {
                bool result = false;
                e.REF_PHASE_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.REF_PHASE, global::LightSwitchApplication.REF_PHASE.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.REF_PHASE, global::LightSwitchApplication.REF_PHASE.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.REF_PHASE.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.REF_PHASE, global::LightSwitchApplication.REF_PHASE.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_PHASE, global::LightSwitchApplication.REF_PHASE.DetailsClass, short> PhaseID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.REF_PHASE.DetailsClass.PropertySetProperties.PhaseID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_PHASE, global::LightSwitchApplication.REF_PHASE.DetailsClass, short>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_PHASE, global::LightSwitchApplication.REF_PHASE.DetailsClass, string> Name
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.REF_PHASE.DetailsClass.PropertySetProperties.Name) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_PHASE, global::LightSwitchApplication.REF_PHASE.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_PHASE, global::LightSwitchApplication.REF_PHASE.DetailsClass, string> Description
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.REF_PHASE.DetailsClass.PropertySetProperties.Description) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_PHASE, global::LightSwitchApplication.REF_PHASE.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_PHASE, global::LightSwitchApplication.REF_PHASE.DetailsClass, global::System.Nullable<global::System.DateTime>> CreatedDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.REF_PHASE.DetailsClass.PropertySetProperties.CreatedDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_PHASE, global::LightSwitchApplication.REF_PHASE.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_PHASE, global::LightSwitchApplication.REF_PHASE.DetailsClass, string> CreatedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.REF_PHASE.DetailsClass.PropertySetProperties.CreatedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_PHASE, global::LightSwitchApplication.REF_PHASE.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.REF_PHASE, global::LightSwitchApplication.REF_PHASE.DetailsClass, global::LightSwitchApplication.TP_PHASE> TP_PHASEs
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.REF_PHASE.DetailsClass.PropertySetProperties.TP_PHASEs) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.REF_PHASE, global::LightSwitchApplication.REF_PHASE.DetailsClass, global::LightSwitchApplication.TP_PHASE>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new short PhaseID { get; }
                new string Name { get; set; }
                new string Description { get; set; }
                new global::System.Nullable<global::System.DateTime> CreatedDate { get; set; }
                new string CreatedBy { get; set; }
                new global::System.Collections.IEnumerable TP_PHASEs { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_PHASE, global::LightSwitchApplication.REF_PHASE.DetailsClass, short>.Entry
                    PhaseID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_PHASE, global::LightSwitchApplication.REF_PHASE.DetailsClass, short>.Entry(
                        "PhaseID",
                        global::LightSwitchApplication.REF_PHASE.DetailsClass.PropertySetProperties._PhaseID_Stub,
                        global::LightSwitchApplication.REF_PHASE.DetailsClass.PropertySetProperties._PhaseID_ComputeIsReadOnly,
                        global::LightSwitchApplication.REF_PHASE.DetailsClass.PropertySetProperties._PhaseID_Validate,
                        global::LightSwitchApplication.REF_PHASE.DetailsClass.PropertySetProperties._PhaseID_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.REF_PHASE.DetailsClass.PropertySetProperties._PhaseID_OnValueChanged);
                private static void _PhaseID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.REF_PHASE.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_PHASE, global::LightSwitchApplication.REF_PHASE.DetailsClass, short>.Data> c, global::LightSwitchApplication.REF_PHASE.DetailsClass d, object sf)
                {
                    c(d, ref d._PhaseID, sf);
                }
                private static bool _PhaseID_ComputeIsReadOnly(global::LightSwitchApplication.REF_PHASE e)
                {
                    bool result = false;
                    e.PhaseID_IsReadOnly(ref result);
                    return result;
                }
                private static void _PhaseID_Validate(global::LightSwitchApplication.REF_PHASE e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.PhaseID_Validate(r);
                }
                private static short _PhaseID_GetImplementationValue(global::LightSwitchApplication.REF_PHASE.DetailsClass d)
                {
                    return d.ImplementationEntity.PhaseID;
                }
                private static void _PhaseID_OnValueChanged(global::LightSwitchApplication.REF_PHASE e)
                {
                    e.PhaseID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_PHASE, global::LightSwitchApplication.REF_PHASE.DetailsClass, string>.Entry
                    Name = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_PHASE, global::LightSwitchApplication.REF_PHASE.DetailsClass, string>.Entry(
                        "Name",
                        global::LightSwitchApplication.REF_PHASE.DetailsClass.PropertySetProperties._Name_Stub,
                        global::LightSwitchApplication.REF_PHASE.DetailsClass.PropertySetProperties._Name_ComputeIsReadOnly,
                        global::LightSwitchApplication.REF_PHASE.DetailsClass.PropertySetProperties._Name_Validate,
                        global::LightSwitchApplication.REF_PHASE.DetailsClass.PropertySetProperties._Name_GetImplementationValue,
                        global::LightSwitchApplication.REF_PHASE.DetailsClass.PropertySetProperties._Name_SetImplementationValue,
                        global::LightSwitchApplication.REF_PHASE.DetailsClass.PropertySetProperties._Name_OnValueChanged);
                private static void _Name_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.REF_PHASE.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_PHASE, global::LightSwitchApplication.REF_PHASE.DetailsClass, string>.Data> c, global::LightSwitchApplication.REF_PHASE.DetailsClass d, object sf)
                {
                    c(d, ref d._Name, sf);
                }
                private static bool _Name_ComputeIsReadOnly(global::LightSwitchApplication.REF_PHASE e)
                {
                    bool result = false;
                    e.Name_IsReadOnly(ref result);
                    return result;
                }
                private static void _Name_Validate(global::LightSwitchApplication.REF_PHASE e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Name_Validate(r);
                }
                private static string _Name_GetImplementationValue(global::LightSwitchApplication.REF_PHASE.DetailsClass d)
                {
                    return d.ImplementationEntity.Name;
                }
                private static void _Name_SetImplementationValue(global::LightSwitchApplication.REF_PHASE.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Name = v;
                }
                private static void _Name_OnValueChanged(global::LightSwitchApplication.REF_PHASE e)
                {
                    e.Name_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_PHASE, global::LightSwitchApplication.REF_PHASE.DetailsClass, string>.Entry
                    Description = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_PHASE, global::LightSwitchApplication.REF_PHASE.DetailsClass, string>.Entry(
                        "Description",
                        global::LightSwitchApplication.REF_PHASE.DetailsClass.PropertySetProperties._Description_Stub,
                        global::LightSwitchApplication.REF_PHASE.DetailsClass.PropertySetProperties._Description_ComputeIsReadOnly,
                        global::LightSwitchApplication.REF_PHASE.DetailsClass.PropertySetProperties._Description_Validate,
                        global::LightSwitchApplication.REF_PHASE.DetailsClass.PropertySetProperties._Description_GetImplementationValue,
                        global::LightSwitchApplication.REF_PHASE.DetailsClass.PropertySetProperties._Description_SetImplementationValue,
                        global::LightSwitchApplication.REF_PHASE.DetailsClass.PropertySetProperties._Description_OnValueChanged);
                private static void _Description_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.REF_PHASE.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_PHASE, global::LightSwitchApplication.REF_PHASE.DetailsClass, string>.Data> c, global::LightSwitchApplication.REF_PHASE.DetailsClass d, object sf)
                {
                    c(d, ref d._Description, sf);
                }
                private static bool _Description_ComputeIsReadOnly(global::LightSwitchApplication.REF_PHASE e)
                {
                    bool result = false;
                    e.Description_IsReadOnly(ref result);
                    return result;
                }
                private static void _Description_Validate(global::LightSwitchApplication.REF_PHASE e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Description_Validate(r);
                }
                private static string _Description_GetImplementationValue(global::LightSwitchApplication.REF_PHASE.DetailsClass d)
                {
                    return d.ImplementationEntity.Description;
                }
                private static void _Description_SetImplementationValue(global::LightSwitchApplication.REF_PHASE.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Description = v;
                }
                private static void _Description_OnValueChanged(global::LightSwitchApplication.REF_PHASE e)
                {
                    e.Description_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_PHASE, global::LightSwitchApplication.REF_PHASE.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    CreatedDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_PHASE, global::LightSwitchApplication.REF_PHASE.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "CreatedDate",
                        global::LightSwitchApplication.REF_PHASE.DetailsClass.PropertySetProperties._CreatedDate_Stub,
                        global::LightSwitchApplication.REF_PHASE.DetailsClass.PropertySetProperties._CreatedDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.REF_PHASE.DetailsClass.PropertySetProperties._CreatedDate_Validate,
                        global::LightSwitchApplication.REF_PHASE.DetailsClass.PropertySetProperties._CreatedDate_GetImplementationValue,
                        global::LightSwitchApplication.REF_PHASE.DetailsClass.PropertySetProperties._CreatedDate_SetImplementationValue,
                        global::LightSwitchApplication.REF_PHASE.DetailsClass.PropertySetProperties._CreatedDate_OnValueChanged);
                private static void _CreatedDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.REF_PHASE.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_PHASE, global::LightSwitchApplication.REF_PHASE.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.REF_PHASE.DetailsClass d, object sf)
                {
                    c(d, ref d._CreatedDate, sf);
                }
                private static bool _CreatedDate_ComputeIsReadOnly(global::LightSwitchApplication.REF_PHASE e)
                {
                    bool result = false;
                    e.CreatedDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreatedDate_Validate(global::LightSwitchApplication.REF_PHASE e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreatedDate_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _CreatedDate_GetImplementationValue(global::LightSwitchApplication.REF_PHASE.DetailsClass d)
                {
                    return d.ImplementationEntity.CreatedDate;
                }
                private static void _CreatedDate_SetImplementationValue(global::LightSwitchApplication.REF_PHASE.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.CreatedDate = global::LightSwitchApplication.REF_PHASE.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _CreatedDate_OnValueChanged(global::LightSwitchApplication.REF_PHASE e)
                {
                    e.CreatedDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_PHASE, global::LightSwitchApplication.REF_PHASE.DetailsClass, string>.Entry
                    CreatedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_PHASE, global::LightSwitchApplication.REF_PHASE.DetailsClass, string>.Entry(
                        "CreatedBy",
                        global::LightSwitchApplication.REF_PHASE.DetailsClass.PropertySetProperties._CreatedBy_Stub,
                        global::LightSwitchApplication.REF_PHASE.DetailsClass.PropertySetProperties._CreatedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.REF_PHASE.DetailsClass.PropertySetProperties._CreatedBy_Validate,
                        global::LightSwitchApplication.REF_PHASE.DetailsClass.PropertySetProperties._CreatedBy_GetImplementationValue,
                        global::LightSwitchApplication.REF_PHASE.DetailsClass.PropertySetProperties._CreatedBy_SetImplementationValue,
                        global::LightSwitchApplication.REF_PHASE.DetailsClass.PropertySetProperties._CreatedBy_OnValueChanged);
                private static void _CreatedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.REF_PHASE.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_PHASE, global::LightSwitchApplication.REF_PHASE.DetailsClass, string>.Data> c, global::LightSwitchApplication.REF_PHASE.DetailsClass d, object sf)
                {
                    c(d, ref d._CreatedBy, sf);
                }
                private static bool _CreatedBy_ComputeIsReadOnly(global::LightSwitchApplication.REF_PHASE e)
                {
                    bool result = false;
                    e.CreatedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreatedBy_Validate(global::LightSwitchApplication.REF_PHASE e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreatedBy_Validate(r);
                }
                private static string _CreatedBy_GetImplementationValue(global::LightSwitchApplication.REF_PHASE.DetailsClass d)
                {
                    return d.ImplementationEntity.CreatedBy;
                }
                private static void _CreatedBy_SetImplementationValue(global::LightSwitchApplication.REF_PHASE.DetailsClass d, string v)
                {
                    d.ImplementationEntity.CreatedBy = v;
                }
                private static void _CreatedBy_OnValueChanged(global::LightSwitchApplication.REF_PHASE e)
                {
                    e.CreatedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.REF_PHASE, global::LightSwitchApplication.REF_PHASE.DetailsClass, global::LightSwitchApplication.TP_PHASE>.Entry
                    TP_PHASEs = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.REF_PHASE, global::LightSwitchApplication.REF_PHASE.DetailsClass, global::LightSwitchApplication.TP_PHASE>.Entry(
                        "TP_PHASEs",
                        global::LightSwitchApplication.REF_PHASE.DetailsClass.PropertySetProperties._TP_PHASEs_Stub,
                        global::LightSwitchApplication.REF_PHASE.DetailsClass.PropertySetProperties._TP_PHASEs_GetReferencedEntities,
                        global::LightSwitchApplication.REF_PHASE.DetailsClass.PropertySetProperties._TP_PHASEs_GetEntityCollection);
                private static void _TP_PHASEs_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.REF_PHASE.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.REF_PHASE, global::LightSwitchApplication.REF_PHASE.DetailsClass, global::LightSwitchApplication.TP_PHASE>.Data> c, global::LightSwitchApplication.REF_PHASE.DetailsClass d, object sf)
                {
                    c(d, ref d._TP_PHASEs, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.TP_PHASE> _TP_PHASEs_GetReferencedEntities(global::LightSwitchApplication.REF_PHASE.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.TP_PHASE, global::LightSwitchApplication.TP_PHASE.DetailsClass>(global::LightSwitchApplication.REF_PHASE.DetailsClass.PropertySetProperties.TP_PHASEs, ref d._TP_PHASEs);
                }
                private static global::System.Collections.IEnumerable _TP_PHASEs_GetEntityCollection(global::LightSwitchApplication.REF_PHASE.DetailsClass d)
                {
                    return d.ImplementationEntity.TP_PHASEs;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_PHASE, global::LightSwitchApplication.REF_PHASE.DetailsClass, short>.Data _PhaseID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_PHASE, global::LightSwitchApplication.REF_PHASE.DetailsClass, string>.Data _Name;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_PHASE, global::LightSwitchApplication.REF_PHASE.DetailsClass, string>.Data _Description;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_PHASE, global::LightSwitchApplication.REF_PHASE.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _CreatedDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_PHASE, global::LightSwitchApplication.REF_PHASE.DetailsClass, string>.Data _CreatedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.REF_PHASE, global::LightSwitchApplication.REF_PHASE.DetailsClass, global::LightSwitchApplication.TP_PHASE>.Data _TP_PHASEs;
            
        }
    
        #endregion
    }
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    public sealed partial class REF_RATE_CARD : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.REF_RATE_CARD, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the REF_RATE_CARD entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public REF_RATE_CARD()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public REF_RATE_CARD(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.REF_RATE_CARD> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void REF_RATE_CARD_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void REF_RATE_CARD_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public short RateCardId
        {
            get
            {
                return global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.GetValue(this, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties.RateCardId);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RateCardId_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RateCardId_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RateCardId_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<decimal> Rate
        {
            get
            {
                return global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.GetValue(this, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties.Rate);
            }
            set
            {
                global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.SetValue(this, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties.Rate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Rate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Rate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Rate_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string CreatedBy
        {
            get
            {
                return global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.GetValue(this, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties.CreatedBy);
            }
            set
            {
                global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.SetValue(this, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties.CreatedBy, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> CreatedDate
        {
            get
            {
                return global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.GetValue(this, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties.CreatedDate);
            }
            set
            {
                global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.SetValue(this, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties.CreatedDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedDate_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ModifiedBy
        {
            get
            {
                return global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.GetValue(this, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties.ModifiedBy);
            }
            set
            {
                global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.SetValue(this, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties.ModifiedBy, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> ModifiedDate
        {
            get
            {
                return global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.GetValue(this, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties.ModifiedDate);
            }
            set
            {
                global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.SetValue(this, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties.ModifiedDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedDate_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.REF_LOCATION REF_LOCATION
        {
            get
            {
                return global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.GetValue(this, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties.REF_LOCATION);
            }
            set
            {
                global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.SetValue(this, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties.REF_LOCATION, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void REF_LOCATION_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void REF_LOCATION_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void REF_LOCATION_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.RESOURCE RESOURCE
        {
            get
            {
                return global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.GetValue(this, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties.RESOURCE);
            }
            set
            {
                global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.SetValue(this, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties.RESOURCE, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RESOURCE_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RESOURCE_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RESOURCE_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.REF_RATE_CARD,
                global::LightSwitchApplication.REF_RATE_CARD.DetailsClass,
                global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.IImplementation,
                global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.REF_RATE_CARD, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.REF_RATE_CARD, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties.RateCardId;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.REF_RATE_CARD, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass>.Entry
                __REF_RATE_CARDEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.REF_RATE_CARD, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass>.Entry(
                    global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.__REF_RATE_CARD_CreateNew,
                    global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.__REF_RATE_CARD_Created,
                    global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.__REF_RATE_CARD_AllowSaveWithErrors);
            private static global::LightSwitchApplication.REF_RATE_CARD __REF_RATE_CARD_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.REF_RATE_CARD> es)
            {
                return new global::LightSwitchApplication.REF_RATE_CARD(es);
            }
            private static void __REF_RATE_CARD_Created(global::LightSwitchApplication.REF_RATE_CARD e)
            {
                e.REF_RATE_CARD_Created();
            }
            private static bool __REF_RATE_CARD_AllowSaveWithErrors(global::LightSwitchApplication.REF_RATE_CARD e)
            {
                bool result = false;
                e.REF_RATE_CARD_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.REF_RATE_CARD, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.REF_RATE_CARD, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.REF_RATE_CARD, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_RATE_CARD, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass, short> RateCardId
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties.RateCardId) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_RATE_CARD, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass, short>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_RATE_CARD, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass, global::System.Nullable<decimal>> Rate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties.Rate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_RATE_CARD, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass, global::System.Nullable<decimal>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_RATE_CARD, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass, string> CreatedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties.CreatedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_RATE_CARD, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_RATE_CARD, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass, global::System.Nullable<global::System.DateTime>> CreatedDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties.CreatedDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_RATE_CARD, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_RATE_CARD, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass, string> ModifiedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties.ModifiedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_RATE_CARD, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_RATE_CARD, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass, global::System.Nullable<global::System.DateTime>> ModifiedDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties.ModifiedDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_RATE_CARD, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.REF_RATE_CARD, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass, global::LightSwitchApplication.REF_LOCATION> REF_LOCATION
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties.REF_LOCATION) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.REF_RATE_CARD, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass, global::LightSwitchApplication.REF_LOCATION>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.REF_RATE_CARD, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass, global::LightSwitchApplication.RESOURCE> RESOURCE
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties.RESOURCE) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.REF_RATE_CARD, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass, global::LightSwitchApplication.RESOURCE>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new short RateCardId { get; }
                new global::System.Nullable<decimal> Rate { get; set; }
                new string CreatedBy { get; set; }
                new global::System.Nullable<global::System.DateTime> CreatedDate { get; set; }
                new string ModifiedBy { get; set; }
                new global::System.Nullable<global::System.DateTime> ModifiedDate { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation REF_LOCATION { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation RESOURCE { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_RATE_CARD, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass, short>.Entry
                    RateCardId = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_RATE_CARD, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass, short>.Entry(
                        "RateCardId",
                        global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties._RateCardId_Stub,
                        global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties._RateCardId_ComputeIsReadOnly,
                        global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties._RateCardId_Validate,
                        global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties._RateCardId_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties._RateCardId_OnValueChanged);
                private static void _RateCardId_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.REF_RATE_CARD.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_RATE_CARD, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass, short>.Data> c, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass d, object sf)
                {
                    c(d, ref d._RateCardId, sf);
                }
                private static bool _RateCardId_ComputeIsReadOnly(global::LightSwitchApplication.REF_RATE_CARD e)
                {
                    bool result = false;
                    e.RateCardId_IsReadOnly(ref result);
                    return result;
                }
                private static void _RateCardId_Validate(global::LightSwitchApplication.REF_RATE_CARD e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RateCardId_Validate(r);
                }
                private static short _RateCardId_GetImplementationValue(global::LightSwitchApplication.REF_RATE_CARD.DetailsClass d)
                {
                    return d.ImplementationEntity.RateCardId;
                }
                private static void _RateCardId_OnValueChanged(global::LightSwitchApplication.REF_RATE_CARD e)
                {
                    e.RateCardId_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_RATE_CARD, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass, global::System.Nullable<decimal>>.Entry
                    Rate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_RATE_CARD, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass, global::System.Nullable<decimal>>.Entry(
                        "Rate",
                        global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties._Rate_Stub,
                        global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties._Rate_ComputeIsReadOnly,
                        global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties._Rate_Validate,
                        global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties._Rate_GetImplementationValue,
                        global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties._Rate_SetImplementationValue,
                        global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties._Rate_OnValueChanged);
                private static void _Rate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.REF_RATE_CARD.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_RATE_CARD, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass, global::System.Nullable<decimal>>.Data> c, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass d, object sf)
                {
                    c(d, ref d._Rate, sf);
                }
                private static bool _Rate_ComputeIsReadOnly(global::LightSwitchApplication.REF_RATE_CARD e)
                {
                    bool result = false;
                    e.Rate_IsReadOnly(ref result);
                    return result;
                }
                private static void _Rate_Validate(global::LightSwitchApplication.REF_RATE_CARD e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Rate_Validate(r);
                }
                private static global::System.Nullable<decimal> _Rate_GetImplementationValue(global::LightSwitchApplication.REF_RATE_CARD.DetailsClass d)
                {
                    return d.ImplementationEntity.Rate;
                }
                private static void _Rate_SetImplementationValue(global::LightSwitchApplication.REF_RATE_CARD.DetailsClass d, global::System.Nullable<decimal> v)
                {
                    d.ImplementationEntity.Rate = v;
                }
                private static void _Rate_OnValueChanged(global::LightSwitchApplication.REF_RATE_CARD e)
                {
                    e.Rate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_RATE_CARD, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass, string>.Entry
                    CreatedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_RATE_CARD, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass, string>.Entry(
                        "CreatedBy",
                        global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties._CreatedBy_Stub,
                        global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties._CreatedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties._CreatedBy_Validate,
                        global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties._CreatedBy_GetImplementationValue,
                        global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties._CreatedBy_SetImplementationValue,
                        global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties._CreatedBy_OnValueChanged);
                private static void _CreatedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.REF_RATE_CARD.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_RATE_CARD, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass, string>.Data> c, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass d, object sf)
                {
                    c(d, ref d._CreatedBy, sf);
                }
                private static bool _CreatedBy_ComputeIsReadOnly(global::LightSwitchApplication.REF_RATE_CARD e)
                {
                    bool result = false;
                    e.CreatedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreatedBy_Validate(global::LightSwitchApplication.REF_RATE_CARD e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreatedBy_Validate(r);
                }
                private static string _CreatedBy_GetImplementationValue(global::LightSwitchApplication.REF_RATE_CARD.DetailsClass d)
                {
                    return d.ImplementationEntity.CreatedBy;
                }
                private static void _CreatedBy_SetImplementationValue(global::LightSwitchApplication.REF_RATE_CARD.DetailsClass d, string v)
                {
                    d.ImplementationEntity.CreatedBy = v;
                }
                private static void _CreatedBy_OnValueChanged(global::LightSwitchApplication.REF_RATE_CARD e)
                {
                    e.CreatedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_RATE_CARD, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    CreatedDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_RATE_CARD, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "CreatedDate",
                        global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties._CreatedDate_Stub,
                        global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties._CreatedDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties._CreatedDate_Validate,
                        global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties._CreatedDate_GetImplementationValue,
                        global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties._CreatedDate_SetImplementationValue,
                        global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties._CreatedDate_OnValueChanged);
                private static void _CreatedDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.REF_RATE_CARD.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_RATE_CARD, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass d, object sf)
                {
                    c(d, ref d._CreatedDate, sf);
                }
                private static bool _CreatedDate_ComputeIsReadOnly(global::LightSwitchApplication.REF_RATE_CARD e)
                {
                    bool result = false;
                    e.CreatedDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreatedDate_Validate(global::LightSwitchApplication.REF_RATE_CARD e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreatedDate_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _CreatedDate_GetImplementationValue(global::LightSwitchApplication.REF_RATE_CARD.DetailsClass d)
                {
                    return d.ImplementationEntity.CreatedDate;
                }
                private static void _CreatedDate_SetImplementationValue(global::LightSwitchApplication.REF_RATE_CARD.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.CreatedDate = global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _CreatedDate_OnValueChanged(global::LightSwitchApplication.REF_RATE_CARD e)
                {
                    e.CreatedDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_RATE_CARD, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass, string>.Entry
                    ModifiedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_RATE_CARD, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass, string>.Entry(
                        "ModifiedBy",
                        global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties._ModifiedBy_Stub,
                        global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties._ModifiedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties._ModifiedBy_Validate,
                        global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties._ModifiedBy_GetImplementationValue,
                        global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties._ModifiedBy_SetImplementationValue,
                        global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties._ModifiedBy_OnValueChanged);
                private static void _ModifiedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.REF_RATE_CARD.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_RATE_CARD, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass, string>.Data> c, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifiedBy, sf);
                }
                private static bool _ModifiedBy_ComputeIsReadOnly(global::LightSwitchApplication.REF_RATE_CARD e)
                {
                    bool result = false;
                    e.ModifiedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifiedBy_Validate(global::LightSwitchApplication.REF_RATE_CARD e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifiedBy_Validate(r);
                }
                private static string _ModifiedBy_GetImplementationValue(global::LightSwitchApplication.REF_RATE_CARD.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifiedBy;
                }
                private static void _ModifiedBy_SetImplementationValue(global::LightSwitchApplication.REF_RATE_CARD.DetailsClass d, string v)
                {
                    d.ImplementationEntity.ModifiedBy = v;
                }
                private static void _ModifiedBy_OnValueChanged(global::LightSwitchApplication.REF_RATE_CARD e)
                {
                    e.ModifiedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_RATE_CARD, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    ModifiedDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_RATE_CARD, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "ModifiedDate",
                        global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties._ModifiedDate_Stub,
                        global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties._ModifiedDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties._ModifiedDate_Validate,
                        global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties._ModifiedDate_GetImplementationValue,
                        global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties._ModifiedDate_SetImplementationValue,
                        global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties._ModifiedDate_OnValueChanged);
                private static void _ModifiedDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.REF_RATE_CARD.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_RATE_CARD, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifiedDate, sf);
                }
                private static bool _ModifiedDate_ComputeIsReadOnly(global::LightSwitchApplication.REF_RATE_CARD e)
                {
                    bool result = false;
                    e.ModifiedDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifiedDate_Validate(global::LightSwitchApplication.REF_RATE_CARD e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifiedDate_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _ModifiedDate_GetImplementationValue(global::LightSwitchApplication.REF_RATE_CARD.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifiedDate;
                }
                private static void _ModifiedDate_SetImplementationValue(global::LightSwitchApplication.REF_RATE_CARD.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.ModifiedDate = global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _ModifiedDate_OnValueChanged(global::LightSwitchApplication.REF_RATE_CARD e)
                {
                    e.ModifiedDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.REF_RATE_CARD, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass, global::LightSwitchApplication.REF_LOCATION>.Entry
                    REF_LOCATION = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.REF_RATE_CARD, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass, global::LightSwitchApplication.REF_LOCATION>.Entry(
                        "REF_LOCATION",
                        global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties._REF_LOCATION_Stub,
                        global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties._REF_LOCATION_ComputeIsReadOnly,
                        global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties._REF_LOCATION_Validate,
                        global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties._REF_LOCATION_GetCoreImplementationValue,
                        global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties._REF_LOCATION_GetImplementationValue,
                        global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties._REF_LOCATION_SetImplementationValue,
                        global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties._REF_LOCATION_Refresh,
                        global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties._REF_LOCATION_OnValueChanged);
                private static void _REF_LOCATION_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.REF_RATE_CARD.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.REF_RATE_CARD, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass, global::LightSwitchApplication.REF_LOCATION>.Data> c, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass d, object sf)
                {
                    c(d, ref d._REF_LOCATION, sf);
                }
                private static bool _REF_LOCATION_ComputeIsReadOnly(global::LightSwitchApplication.REF_RATE_CARD e)
                {
                    bool result = false;
                    e.REF_LOCATION_IsReadOnly(ref result);
                    return result;
                }
                private static void _REF_LOCATION_Validate(global::LightSwitchApplication.REF_RATE_CARD e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.REF_LOCATION_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _REF_LOCATION_GetCoreImplementationValue(global::LightSwitchApplication.REF_RATE_CARD.DetailsClass d)
                {
                    return d.ImplementationEntity.REF_LOCATION;
                }
                private static global::LightSwitchApplication.REF_LOCATION _REF_LOCATION_GetImplementationValue(global::LightSwitchApplication.REF_RATE_CARD.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.REF_LOCATION, global::LightSwitchApplication.REF_LOCATION.DetailsClass>(global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties.REF_LOCATION, ref d._REF_LOCATION);
                }
                private static void _REF_LOCATION_SetImplementationValue(global::LightSwitchApplication.REF_RATE_CARD.DetailsClass d, global::LightSwitchApplication.REF_LOCATION v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties.REF_LOCATION, ref d._REF_LOCATION, (i, ev) => i.REF_LOCATION = ev, v);
                }
                private static void _REF_LOCATION_Refresh(global::LightSwitchApplication.REF_RATE_CARD.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties.REF_LOCATION, ref d._REF_LOCATION);
                }
                private static void _REF_LOCATION_OnValueChanged(global::LightSwitchApplication.REF_RATE_CARD e)
                {
                    e.REF_LOCATION_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.REF_RATE_CARD, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass, global::LightSwitchApplication.RESOURCE>.Entry
                    RESOURCE = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.REF_RATE_CARD, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass, global::LightSwitchApplication.RESOURCE>.Entry(
                        "RESOURCE",
                        global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties._RESOURCE_Stub,
                        global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties._RESOURCE_ComputeIsReadOnly,
                        global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties._RESOURCE_Validate,
                        global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties._RESOURCE_GetCoreImplementationValue,
                        global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties._RESOURCE_GetImplementationValue,
                        global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties._RESOURCE_SetImplementationValue,
                        global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties._RESOURCE_Refresh,
                        global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties._RESOURCE_OnValueChanged);
                private static void _RESOURCE_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.REF_RATE_CARD.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.REF_RATE_CARD, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass, global::LightSwitchApplication.RESOURCE>.Data> c, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass d, object sf)
                {
                    c(d, ref d._RESOURCE, sf);
                }
                private static bool _RESOURCE_ComputeIsReadOnly(global::LightSwitchApplication.REF_RATE_CARD e)
                {
                    bool result = false;
                    e.RESOURCE_IsReadOnly(ref result);
                    return result;
                }
                private static void _RESOURCE_Validate(global::LightSwitchApplication.REF_RATE_CARD e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RESOURCE_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _RESOURCE_GetCoreImplementationValue(global::LightSwitchApplication.REF_RATE_CARD.DetailsClass d)
                {
                    return d.ImplementationEntity.RESOURCE;
                }
                private static global::LightSwitchApplication.RESOURCE _RESOURCE_GetImplementationValue(global::LightSwitchApplication.REF_RATE_CARD.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass>(global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties.RESOURCE, ref d._RESOURCE);
                }
                private static void _RESOURCE_SetImplementationValue(global::LightSwitchApplication.REF_RATE_CARD.DetailsClass d, global::LightSwitchApplication.RESOURCE v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties.RESOURCE, ref d._RESOURCE, (i, ev) => i.RESOURCE = ev, v);
                }
                private static void _RESOURCE_Refresh(global::LightSwitchApplication.REF_RATE_CARD.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.REF_RATE_CARD.DetailsClass.PropertySetProperties.RESOURCE, ref d._RESOURCE);
                }
                private static void _RESOURCE_OnValueChanged(global::LightSwitchApplication.REF_RATE_CARD e)
                {
                    e.RESOURCE_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_RATE_CARD, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass, short>.Data _RateCardId;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_RATE_CARD, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass, global::System.Nullable<decimal>>.Data _Rate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_RATE_CARD, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass, string>.Data _CreatedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_RATE_CARD, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _CreatedDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_RATE_CARD, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass, string>.Data _ModifiedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.REF_RATE_CARD, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _ModifiedDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.REF_RATE_CARD, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass, global::LightSwitchApplication.REF_LOCATION>.Data _REF_LOCATION;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.REF_RATE_CARD, global::LightSwitchApplication.REF_RATE_CARD.DetailsClass, global::LightSwitchApplication.RESOURCE>.Data _RESOURCE;
            
        }
    
        #endregion
    }
    
    #endregion
}
