// Warning: AutoGenerated file, Don't edit.
document.writeln("<script type=\"text/javascript\" src=\"Screens/Application/AddEditAPPLICATION1.lsml.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"Screens/Charts/ResourceNameFilterChart.lsml.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"Screens/Charts/TPFilterReportChart.lsml.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"Screens/Home/Home.lsml.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"Screens/Home/Home_POC.lsml.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"Screens/Reports/BrowseFilter_PMApprovalReport.lsml.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"Screens/Reports/BrowseFilter_PMApprovalReport1.lsml.js\"></script>");
